services:
  - type: web
    name: bpi-ibm-qa-chatbot
    runtime: python
    buildCommand: pip install -r backend/requirements.txt && python ingest.py --path /app/docs
    startCommand: python backend/main_cloud.py
    envVars:
      - key: GROQ_API_KEY
        sync: false   # you enter this manually in Render dashboard
      - key: BPI_DOCS_PATH
        value: /app/docs
      - key: PYTHONPATH
        value: /app
    disk:
      name: vectorstore
      mountPath: /app/vectorstore
      sizeGB: 1
